Repository woowacourse-teams/2024-pengcook, pull requests merged in 2024-07, with the labels that each got.

#12 :sparkles: add main navigation component
  android/app/build.gradle.kts
  android/app/src/main/java/net/pengcook/android/MainActivity.kt
  android/app/src/main/java/net/pengcook/android/MainFragment.kt
  android/app/src/main/res/layout/activity_main.xml
  android/app/src/main/res/layout/fragment_main.xml
  android/app/src/main/res/navigation/nav_graph_main.xml
  android/app/src/main/res/values/strings.xml
Labels: :sparkles: feature

#50 ✨ apply Jasypt to protect important configuration files
  backend/.gitignore
  backend/build.gradle
  backend/src/main/java/net/pengcook/recipe/repository/RecipeRepository.java
  backend/src/main/resources/application-dev.yaml
  backend/src/main/resources/application-local.yaml
  backend/src/main/resources/application-test.yaml
  backend/src/main/resources/docker-compose-local.yaml
  backend/src/test/java/net/pengcook/PengcookApplicationTests.java
Labels: :sparkles: feature, BE

#52 :sparkles: setup basic exception handling
  backend/src/main/java/net/pengcook/category/exception/CategoryException.java
  backend/src/main/java/net/pengcook/exception/DomainException.java
  backend/src/main/java/net/pengcook/exception/GlobalExceptionHandler.java
  backend/src/main/java/net/pengcook/ingredient/exception/IngredientException.java
  backend/src/main/java/net/pengcook/recipe/exception/RecipeException.java
  backend/src/main/java/net/pengcook/user/exception/UserException.java
Labels: :sparkles: feature, BE

#71 🐛 fix build when deploying
  .github/workflows/be-cd.yaml
Labels: :construction_worker: CI, BE

#76 :fire: remove unnecessary code
  backend/src/main/java/net/pengcook/user/domain/User.java
Labels: BE

#79 :truck: change package structure
  android/app/build.gradle.kts
  android/app/src/main/AndroidManifest.xml
  android/app/src/main/java/net/pengcook/android/data/datasource/FeedPagingSource.kt
  android/app/src/main/java/net/pengcook/android/data/model/.gitkeep
  android/app/src/main/java/net/pengcook/android/data/remote/api/.gitkeep
  android/app/src/main/java/net/pengcook/android/data/repository/DummyFeedsRepository.kt
  android/app/src/main/java/net/pengcook/android/listner/FeedItemEventListener.kt
  android/app/src/main/java/net/pengcook/android/presentation/BindingAdapters.kt
  android/app/src/main/java/net/pengcook/android/presentation/MainActivity.kt
  android/app/src/main/java/net/pengcook/android/presentation/core/model/Comment.kt
  android/app/src/main/java/net/pengcook/android/presentation/core/model/Feed.kt
  android/app/src/main/java/net/pengcook/android/presentation/core/model/Recipe.kt
  android/app/src/main/java/net/pengcook/android/presentation/core/model/User.kt
  android/app/src/main/java/net/pengcook/android/presentation/home/FeedRecyclerViewAdapter.kt
  android/app/src/main/java/net/pengcook/android/presentation/home/HomeFragment.kt
  android/app/src/main/java/net/pengcook/android/presentation/home/HomeViewModel.kt
  android/app/src/main/java/net/pengcook/android/presentation/home/listener/FeedItemEventListener.kt
  android/app/src/main/res/layout/activity_main.xml
  android/app/src/main/res/layout/fragment_home.xml
  android/app/src/main/res/layout/item_feed.xml
  android/app/src/main/res/navigation/nav_graph.xml
Labels: AN, :package: package

#82 :recycle: modify RecipeService method access modifier
  backend/src/main/java/net/pengcook/recipe/service/RecipeService.java
Labels: BE

#101 ♻ change return type of feed repository
  android/app/src/main/java/net/pengcook/android/data/datasource/FeedPagingSource.kt
  android/app/src/main/java/net/pengcook/android/data/model/feed/item/FeedItemResponse.kt
  android/app/src/main/java/net/pengcook/android/data/repository/DummyFeedsRepository.kt
  android/app/src/main/java/net/pengcook/android/data/repository/feed/DefaultFeedRepository.kt
  android/app/src/main/java/net/pengcook/android/data/repository/feed/FeedRepository.kt
  android/app/src/main/java/net/pengcook/android/data/util/mapper/FeedMapper.kt
  android/app/src/main/java/net/pengcook/android/presentation/core/model/Feed.kt
  android/app/src/main/java/net/pengcook/android/presentation/core/model/Ingredient.kt
  android/app/src/main/java/net/pengcook/android/presentation/core/model/Recipe.kt
  android/app/src/main/java/net/pengcook/android/presentation/home/FeedRecyclerViewAdapter.kt
  android/app/src/main/java/net/pengcook/android/presentation/home/HomeViewModel.kt
  android/app/src/main/java/net/pengcook/android/presentation/home/listener/FeedItemEventListener.kt
  android/app/src/main/res/layout/item_feed.xml
Labels: :sparkles: feature, AN, 💄 UI

#116 ✨ create login test annotation
  backend/src/test/java/net/pengcook/authentication/annotation/WithLoginUser.java
  backend/src/test/java/net/pengcook/authentication/annotation/WithLoginUserTest.java
  backend/src/test/java/net/pengcook/authentication/extension/LoginExtension.java
Labels: :sparkles: feature, BE

#126 :bug: fix username check api docs
  backend/src/test/java/net/pengcook/user/controller/UserControllerTest.java
Labels: docs, BE, :bug: bug

#127 ✨ add recipe retrieval docs
  backend/src/test/java/net/pengcook/recipe/controller/RecipeControllerTest.java
Labels: :sparkles: feature, BE

#130 :fire: remove birthday code
  backend/src/main/java/net/pengcook/authentication/dto/GoogleSignUpRequest.java
  backend/src/main/java/net/pengcook/authentication/dto/GoogleSignUpResponse.java
  backend/src/main/java/net/pengcook/authentication/service/LoginService.java
  backend/src/main/java/net/pengcook/user/domain/User.java
  backend/src/main/java/net/pengcook/user/dto/UserResponse.java
  backend/src/test/java/net/pengcook/authentication/annotation/WithLoginUser.java
  backend/src/test/java/net/pengcook/authentication/controller/LoginControllerTest.java
  backend/src/test/java/net/pengcook/authentication/extension/LoginExtension.java
  backend/src/test/java/net/pengcook/authentication/service/LoginServiceTest.java
  backend/src/test/java/net/pengcook/category/service/CategoryServiceTest.java
  backend/src/test/java/net/pengcook/user/controller/UserControllerTest.java
  backend/src/test/java/net/pengcook/user/service/UserServiceTest.java
  backend/src/test/resources/data/category.sql
  backend/src/test/resources/data/ingredient.sql
  backend/src/test/resources/data/recipe.sql
  backend/src/test/resources/data/users.sql
Labels: BE
