Repository woowacourse-teams/2024-pengcook, pull requests merged in 2024-08, with the labels that each got.

#136 ✨ add metric monitoring dashboard
  backend/build.gradle
  backend/src/main/resources/application-dev.yaml
  backend/src/main/resources/application-local.yaml
  backend/src/main/resources/docker-compose-dev.yaml
  backend/src/main/resources/docker-compose-local.yaml
Labels: :sparkles: feature, BE

#142 🐛 show log on console
  backend/src/main/resources/logback-spring.xml
Labels: BE, :bug: bug

#146 :zap: set restart options on containers
  backend/src/main/resources/docker-compose-dev.yaml
  backend/src/main/resources/docker-compose-local.yaml
Labels: :sparkles: feature, BE

#198 :recycle: remove prefix api on all endpoints
  backend/src/main/java/net/pengcook/authentication/controller/LoginController.java
  backend/src/main/java/net/pengcook/comment/controller/CommentController.java
  backend/src/main/java/net/pengcook/like/controller/RecipeLikeController.java
  backend/src/main/java/net/pengcook/recipe/controller/RecipeController.java
  backend/src/main/java/net/pengcook/user/controller/UserController.java
  backend/src/test/java/net/pengcook/authentication/controller/LoginControllerTest.java
  backend/src/test/java/net/pengcook/comment/controller/CommentControllerTest.java
  backend/src/test/java/net/pengcook/like/controller/RecipeLikeControllerTest.java
  backend/src/test/java/net/pengcook/recipe/controller/RecipeControllerTest.java
  backend/src/test/java/net/pengcook/user/aop/BlockedUserFilterAspectTest.java
  backend/src/test/java/net/pengcook/user/controller/UserControllerTest.java
Labels: :sparkles: feature, BE

#185 ⚡ prevent to run cd concurrently
  .github/workflows/be-cd.yaml
  .github/workflows/be-ci.yaml
Labels: :construction_worker: CI, BE

#205 :bug: change field to ref
  .github/workflows/be-cd.yaml
Labels: BE, :bug: bug

#232 :technologist: add issue automation
  .github/issue-branch.yaml
  .github/workflows/issue-automation.yaml
Labels: :construction_worker: CI, BE, AN

#237 ✨ add image field to GoogleSignUpRequest
  backend/src/main/java/net/pengcook/authentication/dto/GoogleSignUpRequest.java
  backend/src/main/java/net/pengcook/authentication/service/LoginService.java
  backend/src/main/java/net/pengcook/user/dto/UpdateProfileRequest.java
  backend/src/test/java/net/pengcook/authentication/controller/LoginControllerTest.java
  backend/src/test/java/net/pengcook/authentication/service/LoginServiceTest.java
Labels: :sparkles: feature, BE

#238 :sparkles: delete categoryRecipe by recipe
  backend/src/main/java/net/pengcook/category/repository/CategoryRecipeRepository.java
  backend/src/main/java/net/pengcook/category/service/CategoryService.java
  backend/src/test/java/net/pengcook/category/service/CategoryServiceTest.java
Labels: :sparkles: feature, BE

#234 :sparkles: delete comment by commentId
  backend/src/main/java/net/pengcook/comment/controller/CommentController.java
  backend/src/main/java/net/pengcook/comment/exception/UnauthorizedDeletionException.java
  backend/src/main/java/net/pengcook/comment/service/CommentService.java
  backend/src/test/java/net/pengcook/comment/controller/CommentControllerTest.java
  backend/src/test/java/net/pengcook/comment/service/CommentServiceTest.java
Labels: :sparkles: feature, BE

#241 :recycle: change package of RecipeOfCategoryRequest
  backend/src/main/java/net/pengcook/recipe/controller/RecipeController.java
  backend/src/main/java/net/pengcook/recipe/dto/RecipeOfCategoryRequest.java
  backend/src/main/java/net/pengcook/recipe/service/RecipeService.java
  backend/src/test/java/net/pengcook/recipe/service/RecipeServiceTest.java
Labels: :sparkles: feature, BE
